# Generated by Django 5.2.3 on 2025-06-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adage_id', models.IntegerField(default=None)),
                ('adage_text', models.CharField(max_length=200)),
                ('adage_meaning', models.CharField(max_length=200)),
                ('review_status', models.BooleanField(default=False)),
            ],
        ),
    ]
